//************************************************************************************
//**  
//**  File name:     D:\_Project\Tester_tiny13\src_v1.1_25R\Data.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Monday, July 31, 2023 11:36:51
//**  Licence:       Professional
//**  Registered to: Oleg
//**  Licence key:   5T882T
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_AVR

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 2
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 1
#define MX_USES_UINT32 0
//??????????? ??? ????????????????
#define FC_CAL_AVR
#define MX_TINY
#define MX_ADC
#define MX_ADC_TYPE_5
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_SIZE 64
#define MX_PWM
#define MX_PWMTYPE 1
#define MX_PWM_CNT 2
#define MX_PWM_TMR0_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA8
#define MX_PWM_PSCA64
#define MX_PWM_PSCA256
#define MX_PWM_PSCA1024
#define MX_PWM_1_PORT PORTB
#define MX_PWM_1_TRIS DDRB
#define MX_PWM_1_PIN 0
#define MX_PWM_2_PORT PORTB
#define MX_PWM_2_TRIS DDRB
#define MX_PWM_2_PIN 1

//???????
#define F_CPU 9600000UL
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <avr\io.h>
#include <avr\interrupt.h>
#include <avr\eeprom.h>
#include <avr\wdt.h>

//????????????

//?????????? ???????
#include "C:\Program Files (x86)\Flowcode(AVR)\v5\FCD\internals.c"

//?????????? ???????
void FCM_LED();


//?????????? ??????????
#define FCSZ_LED 4
#define FCV_TRUE (1)
#define FCV_FALSE (0)
volatile MX_UINT16 FCV_U = (0x0);
volatile MX_UINT8 FCV_MODE;
volatile MX_UINT8 FCV_ACK;
volatile MX_CHAR FCV_LED[FCSZ_LED];




//ADC(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Which ADC Channel
c = Acquisition time
d = Conversion Speed
e = VRef+ Option
f = VRef Voltage x 0.01V
******************************/

//Common Defines

#define ADC_1_MX_ADC_CHANNEL	2
#define ADC_1_MX_ADC_ACTIME	40
#define ADC_1_MX_ADC_CONVSP	6
#define ADC_1_MX_ADC_VREFOP	1 //254
#define ADC_1_MX_ADC_VREFVOL	110

#ifndef MX_ADC_CHANNEL_2
 #define MX_ADC_CHANNEL_2			//Inform CAL ADC channel 2 is now in use.
#endif

#ifndef MX_ADC_REF					//Inform CAL ADC peripheral is now in use
 #define MX_ADC_REF
#endif

extern void FC_CAL_Enable_ADC (MX_UINT8 Channel, MX_UINT8 Conv_Speed, MX_UINT8 Vref, MX_UINT8 T_Charge);
extern MX_UINT16 FC_CAL_Sample_ADC (MX_UINT8 Sample_Mode);
extern void FC_CAL_Disable_ADC (void);




//ADC(0): //?????????? ???????

static void FCD_ADC0_SampleADC();
static MX_UINT8 FCD_ADC0_ReadAsByte();
static MX_UINT16 FCD_ADC0_ReadAsInt();
static MX_FLOAT FCD_ADC0_ReadAsVoltage();
static void FCD_ADC0_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE);
static void FCD_ADC0_ADC_RAW_Configure_Channel();
static MX_UINT8 FCD_ADC0_ADC_RAW_Sample_Channel_Byte();
static MX_UINT16 FCD_ADC0_ADC_RAW_Sample_Channel_Int();
static MX_UINT8 FCD_ADC0_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
static MX_UINT16 FCD_ADC0_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
static void FCD_ADC0_ADC_RAW_Disable_Channel();


//Custom(0): //Defines:
/////????????? ??? ?????? ? ??????? TM1637///

//Global Definitions

#define CLK_PIN1 2
#define CLK_PORT1 portb
#define CLK_TRIS1 trisb
#define BitCLK_0         FC_CAL_Bit_Low_DDR (CLK_PORT1, CLK_TRIS1 , CLK_PIN1)
#define BitCLK_F 	     FC_CAL_Bit_In_DDR  (CLK_PORT1, CLK_TRIS1 , CLK_PIN1)

#define DATA_PIN 1
#define DATA_PORT portb
#define DATA_TRIS trisb
#define DATA_0          FC_CAL_Bit_Low_DDR (DATA_PORT, DATA_TRIS , DATA_PIN)
#define DATA_F 			FC_CAL_Bit_In_DDR  (DATA_PORT, DATA_TRIS , DATA_PIN)

MX_UINT8 symbol[20] = {0x3f,0x06,0x5b,0x4f,0x66,0x6d,0x7d,0x07,0x7f,0x6f,0x00,0x40,0x63,0x39,0x01,0x08,0x5C,0x1C};//0~9," ","-",*,?,^,_,o,u 




//Custom(0): //?????????? ???????

static void FCD_Custom0_READ_ME();
static void FCD_Custom0_I2CStart();
static void FCD_Custom0_I2Cask();
static void FCD_Custom0_I2CStop();
static void FCD_Custom0_I2CWrByte(char oneByte);
static void FCD_Custom0_show_digit(char DOT, char bright, char digit1, char digit2, char digit3, char digit4);
static void FCD_Custom0_display_OFF();



//ADC(0): //?????????? ???????


static void FCD_ADC0_SampleADC()
{
	
	    //unused

}

static MX_UINT8 FCD_ADC0_ReadAsByte()
{
	
		MX_UINT8 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_1_MX_ADC_CHANNEL , ADC_1_MX_ADC_CONVSP , ADC_1_MX_ADC_VREFOP , ADC_1_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 0 );				//Perform Sample - Return as byte

		FC_CAL_Disable_ADC ();

		return (retVal);

}

static MX_UINT16 FCD_ADC0_ReadAsInt()
{
	
		MX_UINT16 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_1_MX_ADC_CHANNEL , ADC_1_MX_ADC_CONVSP , ADC_1_MX_ADC_VREFOP , ADC_1_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 1 );				//Perform Sample - Return as MX_UINT16

		FC_CAL_Disable_ADC ();

		return (retVal);

}

static MX_FLOAT FCD_ADC0_ReadAsVoltage()
{
	
		MX_UINT16 iSample;
		MX_FLOAT fSample, fVoltage, fVperDiv;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_1_MX_ADC_CHANNEL , ADC_1_MX_ADC_CONVSP , ADC_1_MX_ADC_VREFOP , ADC_1_MX_ADC_ACTIME );

	  #ifdef MX_ADC_BITS_8
		iSample = FC_CAL_Sample_ADC( 0 );								//Perform Sample - Return as byte
	  #else
		iSample = FC_CAL_Sample_ADC( 1 );								//Perform Sample - Return as MX_UINT16
	  #endif

	  	FC_CAL_Disable_ADC ();											//Switch off ADC peripheral
		fVoltage = flt_fromi( ADC_1_MX_ADC_VREFVOL );						//Convert reference voltage count to floating point (0 - 500 x 10mV)
		fVoltage = flt_mul(fVoltage, 0.01);								//Convert reference voltage count to actual voltage (0 - 5)

	  #ifdef MX_ADC_BITS_8
		fVperDiv = flt_mul(fVoltage, 0.00390625);						//Convert actual voltage to voltage per division (VRef / 256)
	  #endif
	  #ifdef MX_ADC_BITS_10
		fVperDiv = flt_mul(fVoltage, 0.000976);							//Convert actual voltage to voltage per division (VRef / 1024)
	  #endif
	  #ifdef MX_ADC_BITS_12
		fVperDiv = flt_mul(fVoltage, 0.00024414);						//Convert actual voltage to voltage per division (VRef / 4096)
	  #endif

		fSample = flt_fromi(iSample);									//Convert to floating point variable
		fVoltage = flt_mul(fSample, fVperDiv);							//Calculate floating point voltage

		return (fVoltage);

}

static void FCD_ADC0_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE)
{
	
		MX_FLOAT fVoltage;

		fVoltage = FCD_ADC0_ReadAsVoltage();
		FCI_FLOAT_TO_STRING(fVoltage, 2, FCR_RETVAL, FCR_RETVAL_SIZE);	//Convert to String

}

static void FCD_ADC0_ADC_RAW_Configure_Channel()
{
	
		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_1_MX_ADC_CHANNEL , ADC_1_MX_ADC_CONVSP , ADC_1_MX_ADC_VREFOP , ADC_1_MX_ADC_ACTIME );

}

static MX_UINT8 FCD_ADC0_ADC_RAW_Sample_Channel_Byte()
{
	
		return FC_CAL_Sample_ADC( 0 );									//Perform Sample - Return as byte

}

static MX_UINT16 FCD_ADC0_ADC_RAW_Sample_Channel_Int()
{
	
		return FC_CAL_Sample_ADC( 1 );									//Perform Sample - Return as MX_UINT16

}

static MX_UINT8 FCD_ADC0_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 0 );					//Perform Sample - Return as byte - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0xFF);										//Return average as byte

}

static MX_UINT16 FCD_ADC0_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 1 );					//Perform Sample - Return as MX_UINT16 - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0x1FFF);										//Return average as MX_SINT16

}

static void FCD_ADC0_ADC_RAW_Disable_Channel()
{
	
		FC_CAL_Disable_ADC ();											//Disable ADC Channel

}



//Custom(0): //?????????? ???????


static void FCD_Custom0_READ_ME()
{
	
		//To use this component, add new functions via
		//the "Customize Component Code" window

}

static void FCD_Custom0_I2CStart()
{
	BitCLK_F;
	DATA_F;
	delay_us(20);
	DATA_0;
}

static void FCD_Custom0_I2Cask()
{
	BitCLK_0;
	DATA_F;
	delay_us(20); 
	while (FCV_ACK>0) // ???? ???????? 0 ?? ?????
	    {
	     FCV_ACK = FC_CAL_Bit_In(DATA_PORT, DATA_PIN);		
	    }
	BitCLK_F;
	delay_us(20);
	BitCLK_0; 
}

static void FCD_Custom0_I2CStop()
{
	BitCLK_0;
	delay_us(20);
	DATA_0;
	delay_us(20);
	BitCLK_F;
	delay_us(20);
	DATA_F; 
}

static void FCD_Custom0_I2CWrByte(char oneByte)
{
	unsigned char i;
	for (i=0; i<8; i++)
	{
	BitCLK_0;
	if (oneByte & 0x01) 
	{DATA_F;}
	else {DATA_0;}
	delay_us(20);
	 oneByte = oneByte>>1;
	BitCLK_F;
	delay_us(20);
	} 
}

static void FCD_Custom0_show_digit(char DOT, char bright, char digit1, char digit2, char digit3, char digit4)
{
	MX_UINT8 number[4] = {digit1,digit2,digit3,digit4};
	MX_UINT8 i; 
	FCD_Custom0_I2CStart();
	FCD_Custom0_I2CWrByte(0xC0); // ????? ?????? ??????
	FCD_Custom0_I2Cask();
	for (i=0; i<4; i++)
	{
	  if (DOT == 1)
	    {
	     symbol[number[i]]=symbol[number[i]] | 0b10000000;
	    }
	     else 
	       {
	        symbol[number[i]]=symbol[number[i]] & 0b01111111;
	       }
	  FCD_Custom0_I2CWrByte(symbol[number[i]]); // Send data
	  FCD_Custom0_I2Cask();
	}
	FCD_Custom0_I2CStop();
	bright=bright+0x88;
	FCD_Custom0_I2CStart();
	FCD_Custom0_I2CWrByte(bright); // ??????? ???????
	FCD_Custom0_I2Cask();
	FCD_Custom0_I2CStop(); 
}

static void FCD_Custom0_display_OFF()
{
	FCD_Custom0_I2CStart();
	FCD_Custom0_I2CWrByte(0x80); // ????????? ???????
	FCD_Custom0_I2Cask();
	FCD_Custom0_I2CStop(); 
}

#include "C:\Program Files (x86)\Flowcode(AVR)\v5\CAL\includes.c"

//?????????? ???????


void FCM_LED()
{

	//???????????:
	//40bit=1v
	//Umax=25.6v
	//if 1000bit=max
	//to Umax=25v

	//??????????
	//??????????:
	//  led[0] = 0
	//  led[1] = 0
	//  led[2] = 0
	//  //led[3] = 0
	FCV_LED[0] = 0;
	FCV_LED[1] = 0;
	FCV_LED[2] = 0;

	#if 0 // Disabled code
	//???????
	//???????: u > 1020?
	if (FCV_U > 1020)
	{

		//???????????:
		//hi level

		//??????????
		//??????????:
		//  led[3] = 14 //^
		//  //u = 0
		FCV_LED[3] = 14;

	// } else {

	}

	#endif // #if 0: Disabled code
	//????? ??????????
	//????? ??????????: [A]: A
FCC_LED_A:
;

	//???????
	//???????: u >= 400?
	if (FCV_U >= 400)
	{

		//??????????
		//??????????:
		//  led[0] = led[0] + 1
		//  u = u - 400
		FCV_LED[0] = FCV_LED[0] + 1;
		FCV_U = FCV_U - 400;

		//??????? ? ????? ??????????
		//??????? ? ????? ??????????: [A]: A
		goto FCC_LED_A;

	// } else {

	}

	//????? ??????????
	//????? ??????????: [B]: B
FCC_LED_B:
;

	//???????
	//???????: u >= 40?
	if (FCV_U >= 40)
	{

		//??????????
		//??????????:
		//  led[1] = led[1] + 1
		//  u = u - 40
		FCV_LED[1] = FCV_LED[1] + 1;
		FCV_U = FCV_U - 40;

		//??????? ? ????? ??????????
		//??????? ? ????? ??????????: [B]: B
		goto FCC_LED_B;

	// } else {

	}

	//????? ??????????
	//????? ??????????: [C]: C
FCC_LED_C:
;

	//???????
	//???????: u >= 4?
	if (FCV_U >= 4)
	{

		//??????????
		//??????????:
		//  led[2] = led[2] + 1
		//  u = u - 4
		FCV_LED[2] = FCV_LED[2] + 1;
		FCV_U = FCV_U - 4;

		//??????? ? ????? ??????????
		//??????? ? ????? ??????????: [C]: C
		goto FCC_LED_C;

	// } else {

	}

	#if 0 // Disabled code
	//???????
	//???????: led[0] = 0?
	if (FCV_LED[0] == 0)
	{

		//???????????:
		//space

		//??????????
		//??????????:
		//  led[0] = 10
		FCV_LED[0] = 10;

	// } else {

	}

	#endif // #if 0: Disabled code
}


int main()
{
	//?????????????
	MCUSR=0x00;
	wdt_disable();


	//??? ????????????? ??????????
	
	//???????????:
	//pb0 - LED
	//pb1,pb2 - TM1637
	//pb3 - Mode
	//pb4 - ADC

	//????? ??????????
	//????? ??????????: [A]: A
FCC_Main_A:
;

	//????
	//????: B3 -> mode
	DDRB = DDRB & 0xF7;
	FCV_MODE = ((PINB & 0x08) == 0x08);

	//???????????:
	//mode=0 R meter
	//mode=1 U meter

	//?????? ??????????
	//?????? ??????????: u=?????? ?a? Int()
	FCV_U = FCD_ADC0_ReadAsInt();

	//???????????:
	//ADC=1.1v

	//??????????
	//??????????:
	//  led[3] = 17 //u
	//  //dot = 1
	FCV_LED[3] = 17;

	//???????
	//???????: mode = 0?
	if (FCV_MODE == 0)
	{

		//??????????
		//??????????:
		//  led[3] = 16 //o
		//  //dot = 0
		FCV_LED[3] = 16;

		//???????
		//???????: u < 100?
		if (FCV_U < 100)
		{

			//???????????:
			//U<25* R<5 om
			//U<50* R<10 om
			//U<100 R<25 om

			//?????
			//?????: 1 -> B0
			DDRB = DDRB | 0x01;
			if ((1))
				PORTB = (PORTB & 0xFE) | 0x01;
			else
				PORTB = PORTB & 0xFE;

			//???????????:
			//BIP if R<25 om

		// } else {

		}

	// } else {

	}

	//??????
	//??????: LED()
	FCM_LED();

	//?????? ??????????
	//?????? ??????????: show_digit(mode, 1, led[0], led[1], led[2], led[3])
	FCD_Custom0_show_digit(FCV_MODE, 1, FCV_LED[0], FCV_LED[1], FCV_LED[2], FCV_LED[3]);

	//???????????:
	//0~9
	//10=" "
	//11="-"
	//12=*
	//13=?
	//14=^
	//15=_
	//16=o
	//17=u

	//???????????:
	//5 ??? ? ???

	//????????
	//????????: 200 ??
	delay_ms(200);

	//?????
	//?????: 0 -> B0
	DDRB = DDRB | 0x01;
	if ((0))
		PORTB = (PORTB & 0xFE) | 0x01;
	else
		PORTB = PORTB & 0xFE;

	//??????? ? ????? ??????????
	//??????? ? ????? ??????????: [A]: A
	goto FCC_Main_A;

	mainendloop: goto mainendloop;
}



